spring:
  application:
    name: connectra-backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false # Disabled DB queries run while returning JSON

  security:
    user:
      name: ${SPRING_USER}
      password: ${SPRING_PASSWORD}

# Production default
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

# Default Admin Account (Seeder)
default-admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}