spring:
  application:
    name: connectra-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false # Disabled DB queries run while returning JSON

  security:
    user:
      name: ${SPRING_USER}
      password: ${SPRING_PASSWORD}